/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.17.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/server";
import type * as identity from "../identity";
import type * as messages from "../messages";
import type * as openai from "../openai";
import type * as threads from "../threads";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: ApiFromModules<{
  identity: typeof identity;
  messages: typeof messages;
  openai: typeof openai;
  threads: typeof threads;
}>;
